### ISSUE TITLE
Add long options for the short options

### ISSUE THREAD

**Issue by JotaRandom** [archlinux/asp#13]
Hello,

I was reading and playing with `asp` and noticed you only list short options for options (`-h`, `-v`) but there is no long option.
Is there a possibility to add a long options too like the traditional (that I keep imputing on `asp`) `--help` or `--version`?

some users *cof* prefer the long options other for muscle-memory, scripts, not mistake, consistency.
even `pacman` have long and short so it will be on line with what is on **Arch**.

Note: also `https://git.archlinux.org/`still show abs as official arch linux project.

**Comment by falconindy** [comment]
EWONTFIX
